import Head from 'next/head';
import Script from 'next/script';
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="../public/scripts/font.js"/>
      </Head>

      <main>
      a
      </main>
    </>
  )
}
